CALCULATOR_MOCK = {
  "values": [
    {
      "agent_response": {
        "confidence": {
          "MAC": "High",
          "MAT": "Low",
          "MAV": "High",
          "MPR": "High",
          "MSA": "High",
          "MSC": "High",
          "MSI": "High",
          "MUI": "High",
          "MVA": "Medium",
          "MVC": "High",
          "MVI": "High"
        },
        "modified_metrics": {
          "MAC": "L",
          "MAT": "X",
          "MAV": "A",
          "MPR": "N",
          "MSA": "H",
          "MSC": "H",
          "MSI": "H",
          "MUI": "N",
          "MVA": "H",
          "MVC": "H",
          "MVI": "H"
        },
        "rationale": {
          "MAC": "The attack complexity, as per the asset context, suggests a fully hardened system which typically indicates security enhancements. Additionally, multifactor authentication and network segmentation are in place, requiring more complexity for a successful exploit.",
          "MAT": "Left as Not Defined due to insufficient information about attack prerequisites in the given context.",
          "MAV": "Given that the asset requires physical access and VPN to reach it, as well as being isolated with no external exposure, the attack is likely limited to a logically adjacent topology, such as needing internal or administrative network access.",
          "MPR": "The vulnerability allows for an authentication bypass that results in unauthorized access to password management. This suggests that the attacker requires no privileges prior to exploitation.",
          "MSA": "The vulnerability grants the attacker a high level of control which could potentially result in denial of service or other availability impacts, especially considering the high cascading impact potential and connectivity criticality.",
          "MSC": "The vulnerability allows unauthorized administrative access, which can lead to a total loss of confidentiality as the attacker could potentially access sensitive information, including passwords and possibly user data.",
          "MSI": "The attacker can overwrite any user\"s password, resulting in a total loss of integrity. This allows unauthorized modification of system data and can have serious consequences.",
          "MUI": "The vulnerability can be exploited without interaction from any human user, other than the attacker. This is evident because the attack involves manipulating an endpoint to overwrite user passwords, which typically requires no user interaction.",
          "MVA": "Although the vulnerability description does not specifically mention a denial of service, unauthorized administrative access could lead to actions that affect system availability significantly. Given the system\"s high criticality, its high security requirements for availability, and the lack of redundancy, the impact is rated as high.",
          "MVC": "The vulnerability allows attackers to overwrite administrative passwords, granting unauthorized access to sensitive areas and potentially divulging sensitive information managed by the system. Given the high security requirements for confidentiality and the weak encryption protection level, a high impact on confidentiality is justified.",
          "MVI": "The ability for attackers to overwrite users\" passwords shows a total loss of integrity, as they can perform unauthorized modifications with serious consequences. Considering the high security requirements for integrity and weak encryption, the impact is rated as high."
        },
        "score": 9.4,
        "severity": "Critical"
      },
      "asset": {
        "id": 1,
        "name": "Elber",
        "version": "5.9.0",
        "is_active": True,
        "tp": "application",
        "exposure_level": "physical",
        "network_segmentation": "isolated",
        "firewall_configuration": "block_external_allow_internal_only",
        "vpn_access": "required",
        "ssh_remote_access": "false",
        "physical_access_required": "true",
        "security_controls_waf": "present",
        "security_controls_firewall": "absent",
        "security_controls_ids": "absent",
        "security_controls_ips": "present",
        "security_controls_edr": "absent",
        "system_hardening_level": "fully_hardened",
        "software_patch_level": "outdated",
        "network_access_complexity": "multiple_steps",
        "authentication_requirement": "multi_factor",
        "user_privilege_level_required": "admin_or_elevated",
        "access_control_strength": "moderate",
        "privilege_escalation_protection": "absent",
        "user_awareness_level": "low",
        "security_requirements_confidentiality": "high",
        "security_requirements_integrity": "high",
        "security_requirements_availability": "high",
        "asset_criticality": "high",
        "data_sensitivity": "operationally_critical",
        "encryption_protection_level": "weak",
        "availability_redundancy": "low",
        "asset_dependency_level": "medium",
        "connected_systems_criticality": "high",
        "network_connectivity": "medium",
        "cascading_impact_potential": "high",
        "connection_security_controls": "moderate"
      },
      "rule_base_response": {
        "confidence": {
          "AR": "High",
          "CR": "High",
          "IR": "High",
          "MAC": "Medium",
          "MAT": "Medium",
          "MAV": "High",
          "MPR": "Medium",
          "MSA": "Medium",
          "MSC": "Medium",
          "MSI": "Medium",
          "MUI": "Low",
          "MVA": "Medium",
          "MVC": "Medium",
          "MVI": "Medium"
        },
        "metrics": {
          "AR": "HIGH",
          "CR": "HIGH",
          "IR": "HIGH",
          "MAC": "HIGH",
          "MAT": "PRESENT",
          "MAV": "PHYSICAL",
          "MPR": "HIGH",
          "MSA": "HIGH",
          "MSC": "HIGH",
          "MSI": "HIGH",
          "MUI": "NONE",
          "MVA": "HIGH",
          "MVC": "LOW",
          "MVI": "HIGH"
        },
        "rationale": {
          "AR": "Mapped directly from security_requirements_availability: high.",
          "CR": "Mapped directly from security_requirements_confidentiality: high.",
          "IR": "Mapped directly from security_requirements_integrity: high.",
          "MAC": "Base from network_access_complexity=multiple_steps -> HIGH; hardeners=3 adjusted HIGH->HIGH with hardening/patch signals.",
          "MAT": "Some preconditions (single-factor and/or network isolation/VPN). (auth=multi_factor, MAV=PHYSICAL, access_control_strength=moderate).",
          "MAV": "Derived from reachability and controls: physical_required=True, exposure=physical, firewall=block_external_allow_internal_only, segmentation=isolated, vpn_required=True, ssh_remote_access=False.",
          "MPR": "Base from user_privilege_level_required=admin_or_elevated -> HIGH; no change (access_control_strength=moderate, privilege_escalation_protection=absent).",
          "MSA": "Same adjustment model as MSC.",
          "MSC": "Base=HIGH (internal H) from cascading_impact_potential=high; adjusted by dependency=medium, connected_systems_criticality=high, connection_security_controls=moderate, network_connectivity=medium.",
          "MSI": "Same adjustment model as MSC.",
          "MUI": "No explicit user-step inferred. (tp=application, user_awareness_level=low, MAV=PHYSICAL).",
          "MVA": "Start from asset_criticality=high->HIGH (internal H); availability_redundancy=low, tp=application, network_connectivity=medium -> HIGH.",
          "MVC": "Start from data_sensitivity=operationally_critical->LOW (internal M); encryption=weak and asset_criticality=high with exposure=physical -> LOW.",
          "MVI": "Start from asset_criticality=high->HIGH (internal H); hardening/EDR/firewall and access_control_strength=moderate, patch_level=outdated -> HIGH."
        },
        "score": 6.1,
        "severity": "Medium"
      }
    }
  ],
  "vulnerability_id": 1
}

SCAN_MOCK = [
  {
    "access_control_strength": "strong",
    "asset_criticality": "low",
    "asset_dependency_level": "high",
    "authentication_requirement": "none",
    "availability_redundancy": "high",
    "cascading_impact_potential": "high",
    "connected_systems_criticality": "high",
    "connection_security_controls": "weak",
    "data_sensitivity": "operationally_critical",
    "encryption_protection_level": "strong",
    "exposure_level": "physical",
    "firewall_configuration": "block_internal_external_inbound",
    "id": 1,
    "is_active": True,
    "name": "Elber",
    "network_access_complexity": "multiple_steps",
    "network_connectivity": "low",
    "network_segmentation": "highly_isolated",
    "physical_access_required": "true",
    "privilege_escalation_protection": "absent",
    "security_controls_edr": "present",
    "security_controls_firewall": "present",
    "security_controls_ids": "absent",
    "security_controls_ips": "absent",
    "security_controls_waf": "absent",
    "security_requirements_availability": "high",
    "security_requirements_confidentiality": "low",
    "security_requirements_integrity": "high",
    "software_patch_level": "partially_updated",
    "ssh_remote_access": "true",
    "system_hardening_level": "fully_hardened",
    "tp": "security_tools",
    "user_awareness_level": "low",
    "user_privilege_level_required": "none",
    "version": "5.9.0",
    "vpn_access": "required"
  }
]