# Generated by Django 5.2.5 on 2025-08-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tp', models.CharField(choices=[('database', 'Database'), ('application', 'Application'), ('webserver', 'Webserver'), ('security_tools', 'Security Tools')], max_length=20)),
                ('exposure_level', models.CharField(choices=[('external', 'External'), ('internal', 'Internal'), ('local', 'Local'), ('physical', 'Physical')], max_length=20)),
                ('network_segmentation', models.CharField(choices=[('isolated', 'Isolated'), ('highly_isolated', 'Highly Isolated'), ('none', 'None')], max_length=20)),
                ('firewall_configuration', models.CharField(choices=[('allow_external_inbound', 'Allow External Inbound'), ('block_external_allow_internal_only', 'Block External Allow Internal Only'), ('block_internal_external_inbound', 'Block Internal External Inbound')], max_length=50)),
                ('vpn_access', models.CharField(choices=[('required', 'Required'), ('not_required', 'Not Required')], max_length=20)),
                ('ssh_remote_access', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=5)),
                ('physical_access_required', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=5)),
                ('security_controls_waf', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=7)),
                ('security_controls_firewall', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=7)),
                ('security_controls_ids', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=7)),
                ('security_controls_ips', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=7)),
                ('security_controls_edr', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=7)),
                ('system_hardening_level', models.CharField(choices=[('fully_hardened', 'Fully Hardened'), ('partially_hardened', 'Partially Hardened'), ('not_hardened', 'Not Hardened')], max_length=20)),
                ('software_patch_level', models.CharField(choices=[('up_to_date', 'Up to Date'), ('partially_updated', 'Partially Updated'), ('outdated', 'Outdated')], max_length=20)),
                ('network_access_complexity', models.CharField(choices=[('multiple_steps', 'Multiple Steps'), ('moderate_steps', 'Moderate Steps'), ('direct_access', 'Direct Access')], max_length=20)),
                ('authentication_requirement', models.CharField(choices=[('none', 'None'), ('single_factor', 'Single Factor'), ('multi_factor', 'Multi Factor')], max_length=20)),
                ('user_privilege_level_required', models.CharField(choices=[('none', 'None'), ('basic_user', 'Basic User'), ('admin_or_elevated', 'Admin or Elevated')], max_length=20)),
                ('access_control_strength', models.CharField(choices=[('weak', 'Weak'), ('moderate', 'Moderate'), ('strong', 'Strong')], max_length=10)),
                ('privilege_escalation_protection', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=7)),
                ('user_awareness_level', models.CharField(choices=[('low', 'Low'), ('high', 'High')], max_length=5)),
                ('security_requirements_confidentiality', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('not_defined', 'Not Defined')], max_length=15)),
                ('security_requirements_integrity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('not_defined', 'Not Defined')], max_length=15)),
                ('security_requirements_availability', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('not_defined', 'Not Defined')], max_length=15)),
                ('asset_criticality', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=6)),
                ('data_sensitivity', models.CharField(choices=[('highly_sensitive', 'Highly Sensitive'), ('operationally_critical', 'Operationally Critical'), ('non_sensitive', 'Non-sensitive')], max_length=25)),
                ('encryption_protection_level', models.CharField(choices=[('strong', 'Strong'), ('moderate', 'Moderate'), ('weak', 'Weak')], max_length=8)),
                ('availability_redundancy', models.CharField(choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=8)),
                ('asset_dependency_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=6)),
                ('connected_systems_criticality', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=6)),
                ('network_connectivity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=6)),
                ('cascading_impact_potential', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=6)),
                ('connection_security_controls', models.CharField(choices=[('strong', 'Strong'), ('moderate', 'Moderate'), ('weak', 'Weak')], max_length=8)),
            ],
        ),
    ]
