# Generated by Django 5.2.5 on 2025-08-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='network_connectivity',
            field=models.CharField(choices=[('direct_access', 'Direct access'), ('indirect_access', 'Indirect access'), ('isolated', 'Isolated')], max_length=25),
        ),
    ]
