# Generated by Django 5.2.5 on 2025-09-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_network_connectivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='physical_access_required',
        ),
    ]
