# Generated by Django 5.2.5 on 2025-09-14 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_asset_physical_access_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='access_control_strength',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_dependency_level',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='authentication_requirement',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='cascading_impact_potential',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='connected_systems_criticality',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='connection_security_controls',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='encryption_protection_level',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='exposure_level',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='firewall_configuration',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='network_access_complexity',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='network_connectivity',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='network_segmentation',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='security_controls_edr',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='security_controls_firewall',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='security_controls_ids',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='security_controls_ips',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='security_controls_waf',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='security_requirements_availability',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='security_requirements_confidentiality',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='security_requirements_integrity',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='ssh_remote_access',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='user_privilege_level_required',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='vpn_access',
        ),
        migrations.AddField(
            model_name='asset',
            name='authentication_strength',
            field=models.CharField(choices=[('None', 'No authentication is required for access'), ('Single_Factor', 'Requires a single piece of evidence (e.g., password)'), ('Multi_Factor', 'Requires two or more independent verification methods')], default='Single_Factor', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='data_encryption_level',
            field=models.CharField(choices=[('None', 'Data is stored in plaintext'), ('Weak', 'Uses outdated or easily broken encryption'), ('Strong', 'Uses modern, industry-standard strong encryption (e.g., AES-256)')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='endpoint_protection',
            field=models.CharField(choices=[('Not_Present', 'No EDR or advanced agent installed'), ('Monitoring_Only', 'Agent logs suspicious activity without blocking'), ('Active_Blocking', 'Agent is configured to actively block and quarantine threats')], default='Not_Present', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='network_accessibility',
            field=models.CharField(choices=[('Public_Unprotected', 'Publicly accessible with no WAF/firewall'), ('Public_Behind_WAF', 'Publicly accessible, filtered by a WAF'), ('Private_VPN_Access_Only', 'Reachable only via corporate VPN'), ('Private_Corporate_Network', 'Accessible on the general internal network'), ('Private_Highly_Restricted_Segment', 'Accessible only from a secure, isolated segment'), ('Local_Only', 'Requires local (console) access'), ('Physical_Only', 'Requires physical interaction')], default='Private_Corporate_Network', max_length=40),
        ),
        migrations.AddField(
            model_name='asset',
            name='network_protection',
            field=models.CharField(choices=[('Not_Present', 'No IPS/NGFW inspection is performed'), ('Monitoring_Only', 'IDS is in place (logs but does not block)'), ('Active_Blocking', 'IPS is in place and configured to drop malicious traffic')], default='Not_Present', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='propagation_risk',
            field=models.CharField(choices=[('Low', 'Asset is highly isolated, making lateral movement difficult'), ('Medium', 'Asset is on a standard network with some ability to connect to other systems'), ('High', 'Asset is a prime pivot point (e.g., jump box, domain controller)')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='remote_management_access',
            field=models.CharField(choices=[('Publicly_Exposed', 'Administrative ports are open to the internet'), ('Internal_Only', 'Administrative ports are internal-only'), ('Disabled', 'All remote administrative services are disabled')], default='Internal_Only', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='security_requirement_availability',
            field=models.CharField(choices=[('Low', 'Low Requirement'), ('Medium', 'Medium Requirement'), ('High', 'High Requirement')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='security_requirement_confidentiality',
            field=models.CharField(choices=[('Low', 'Low Requirement'), ('Medium', 'Medium Requirement'), ('High', 'High Requirement')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='security_requirement_integrity',
            field=models.CharField(choices=[('Low', 'Low Requirement'), ('Medium', 'Medium Requirement'), ('High', 'High Requirement')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='subsequent_system_availability_req',
            field=models.CharField(choices=[('Low', 'Low Requirement'), ('Medium', 'Medium Requirement'), ('High', 'High Requirement')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='subsequent_system_confidentiality_req',
            field=models.CharField(choices=[('Low', 'Low Requirement'), ('Medium', 'Medium Requirement'), ('High', 'High Requirement')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='subsequent_system_integrity_req',
            field=models.CharField(choices=[('Low', 'Low Requirement'), ('Medium', 'Medium Requirement'), ('High', 'High Requirement')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_criticality',
            field=models.CharField(choices=[('Low', 'Low: Non-essential asset, minimal operational impact'), ('Medium', 'Medium: Supports important business functions'), ('High', 'High: Supports critical business functions'), ('Mission-Critical', 'Mission-Critical: Core to business survival')], default='Medium', help_text="The asset's operational importance to the business.", max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='availability_redundancy',
            field=models.CharField(choices=[('None', 'Single point of failure; no redundancy'), ('Partial', 'Warm or cold standby systems are available'), ('High', 'Fully redundant with automated, seamless failover')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='data_sensitivity',
            field=models.CharField(choices=[('None', 'Public or non-sensitive data'), ('Internal', 'Internal use only; minor harm if disclosed'), ('Confidential', 'Sensitive data (e.g., PII); significant harm if disclosed'), ('Highly-Restricted', 'Regulated data; severe harm if disclosed')], default='Internal', help_text='Sensitivity of the data the asset handles.', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='privilege_escalation_protection',
            field=models.CharField(choices=[('Present', 'The control is present and active'), ('Absent', 'The control is not present')], default='Absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='software_patch_level',
            field=models.CharField(choices=[('Outdated', 'Missing known critical/high severity patches'), ('Partially_Updated', 'Lags behind the latest patches but criticals are applied'), ('Fully_Patched', 'Robust, automated process ensures patches are applied promptly')], default='Partially_Updated', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='system_hardening_level',
            field=models.CharField(choices=[('Not_Hardened', 'Default, out-of-the-box installation'), ('Partially_Hardened', 'Basic security best practices applied'), ('Fully_Hardened', 'Strictly configured per a security standard (e.g., CIS)')], default='Partially_Hardened', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='user_awareness_level',
            field=models.CharField(choices=[('Untrained', 'Users are not trained on security best practices'), ('Standard', 'Users have received basic security awareness training'), ('Security_Aware', 'Users are well-trained and regularly tested')], default='Standard', max_length=20),
        ),
    ]
