# Generated by Django 5.2.5 on 2025-09-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_asset_access_control_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='integrity_protection_level',
            field=models.CharField(choices=[('None', 'No specific integrity protection mechanisms are in place.'), ('Monitoring', 'File Integrity Monitoring (FIM) or similar logging is active to detect unauthorized changes.'), ('Preventive', 'Strict controls like digital signatures, immutable storage, or HSMs are used to actively prevent modification.')], default='None', max_length=20),
        ),
    ]
