# Generated by Django 5.2.5 on 2025-09-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_integrity_protection_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_criticality',
            field=models.CharField(choices=[('Low', 'Low: Non-essential asset, minimal operational impact'), ('Medium', 'Medium: Supports important business functions'), ('High', 'High: Supports critical business functions'), ('Mission_Critical', 'Mission-Critical: Core to business survival')], default='Medium', help_text="The asset's operational importance to the business.", max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='data_sensitivity',
            field=models.CharField(choices=[('None', 'Public or non-sensitive data'), ('Internal', 'Internal use only; minor harm if disclosed'), ('Confidential', 'Sensitive data (e.g., PII); significant harm if disclosed'), ('Highly_Restricted', 'Regulated data; severe harm if disclosed')], default='Internal', help_text='Sensitivity of the data the asset handles.', max_length=20),
        ),
    ]
