# Generated by Django 5.2.5 on 2025-08-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50)),
                ('cve_description', models.TextField()),
                ('cve_status', models.CharField(max_length=50)),
                ('is_resolve', models.BooleanField(default=False)),
                ('weaknesses', models.JSONField(blank=True, null=True)),
                ('base_vector', models.JSONField(blank=True, null=True)),
                ('agent_response', models.JSONField(blank=True, null=True)),
                ('rule_response', models.JSONField(blank=True, null=True)),
                ('base_score', models.FloatField(blank=True, null=True)),
                ('agent_score', models.FloatField(blank=True, null=True)),
                ('rule_score', models.FloatField(blank=True, null=True)),
                ('cve_response', models.JSONField(blank=True, null=True)),
                ('agent_model', models.CharField(choices=[('gpt_4o', 'gpt-4o'), ('deepseek_chat', 'deepseek-chat')], max_length=32, null=True)),
                ('impacted_assets', models.ManyToManyField(to='assets.asset')),
            ],
        ),
    ]
